import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import CategoryContext from './context/news-category-context'
import Navbar from './header/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'News ID',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <CategoryContext>
        {children }
        </CategoryContext>
        </body>
    </html>
  )
}
